Soru 1)
Dersteki pi sayısını bulma tarzında monte carlo yöntemleri gibi, 1 zarı 10000 kere atıp 1 2 3 4 5 6 sayılarını gelme olasılıkları

In [1]:
import random

sayi = 10000

zar = [0,0,0,0,0,0]

for i in range(sayi):
    x = random.random()
    if x < 1/6:
        zar[0] += 1
    elif x < 2/6:
        zar[1] += 1
    elif x < 3/6:
        zar[2] += 1
    elif x < 4/6:
        zar[3] += 1
    elif x < 5/6:
        zar[4] += 1
    else:
        zar[5] += 1

for i in range(6):
    print(i+1,"gelme olasılığı: ",zar[i]/sayi)

print("Toplam: ",sum(zar)/sayi)

1 gelme olasılığı:  0.1632
2 gelme olasılığı:  0.1732
3 gelme olasılığı:  0.1629
4 gelme olasılığı:  0.1725
5 gelme olasılığı:  0.164
6 gelme olasılığı:  0.1642
Toplam:  1.0


Soru 2)
Marko chain yöntemlerini kullanarak 1 yıllık bir kişinin yemek yeme datasını oluşturarak rastgele (hamburger,pizza, lahmancun olacak sadece)
Hamburger-hamburger,
hamburger-pizza,
hamburger lahmancun gelme olaslıklarını hesaplayınız.
*Not: bunu pizza ve lahmacun içinde yapınız


In [10]:
import random

yemekler = ["hamburger","pizza","lahmacun"]
yemek = [0,0,0]

for i in range(365):
    x = random.random()
    if x < 1/3:
        yemek[0] += 1
    elif x < 2/3:
        yemek[1] += 1
    else:
        yemek[2] += 1

print("Hamburger gelme olasılığı: ",yemek[0]/365)
print("Pizza gelme olasılığı: ",yemek[1]/365)
print("Lahmacun gelme olasılığı: ",yemek[2]/365)


print("Hamburgerden sonra pizza gelme olasılığı: ",yemek[1]/(365-yemek[0]))
print("Hamburgerden sonra lahmacun gelme olasılığı: ",yemek[2]/(365-yemek[0]))
print("Toplam: ",yemek[1]/(365-yemek[0])+yemek[2]/(365-yemek[0]))


print("Pizzadan sonra lahmacun gelme olasılığı: ",yemek[2]/(365-yemek[1]))
print("Pizzadan sonra hamburger gelme olasılığı: ",yemek[0]/(365-yemek[1]))
print("Toplam: ",yemek[2]/(365-yemek[1])+yemek[0]/(365-yemek[1]))


print("Lahmacundan sonra hamburger gelme olasılığı: ",yemek[0]/(365-yemek[2]))
print("Lahmacundan sonra pizza gelme olasılığı: ",yemek[1]/(365-yemek[2]))
print("Toplam: ",yemek[0]/(365-yemek[2])+yemek[1]/(365-yemek[2]))

Hamburger gelme olasılığı:  0.3178082191780822
Pizza gelme olasılığı:  0.3315068493150685
Lahmacun gelme olasılığı:  0.3506849315068493
Hamburgerden sonra pizza gelme olasılığı:  0.4859437751004016
Hamburgerden sonra lahmacun gelme olasılığı:  0.5140562248995983
Toplam:  1.0
Pizzadan sonra lahmacun gelme olasılığı:  0.5245901639344263
Pizzadan sonra hamburger gelme olasılığı:  0.47540983606557374
Toplam:  1.0
Lahmacundan sonra hamburger gelme olasılığı:  0.48945147679324896
Lahmacundan sonra pizza gelme olasılığı:  0.510548523206751
Toplam:  1.0


Soru 3)
2 yıllık altın fiyatı oluşturunuz rastgele 800 ve 1000 arasında
Yine markov chain artış azalış sabit kalma 3 durum. olasılıklarınız çıkarınız.
Örnek ilk veriniz 800 sonraki veriniz 810 bu artış
ilk veriniz 900 sonraki veriniz 850 azalış
850 - 850 ise sabit şekilde kategorik hale getirip markov chain uygulayınız

In [13]:
import random

olasılıklar = ["artış","azalış","sabit"]

altın = [0,0,0]

for i in range(365*2):
    x = random.random()
    if x < 1/3:
        altın[0] += 1
    elif x < 2/3:
        altın[1] += 1
    else:
        altın[2] += 1

print("Artış olasılığı: ",altın[0]/(365*2))
print("Toplam", altın[0]/(365*2)+altın[1]/(365*2)+altın[2]/(365*2))


print("Azalıştan sonra artış olasılığı: ",altın[0]/(365*2-altın[2]))
print("Azalıştan sonra sabit kalma olasılığı: ",altın[1]/(365*2-altın[2]))
print("Toplam: ",altın[0]/(365*2-altın[2])+altın[1]/(365*2-altın[2]))

print("Artıştan sonra azalış olasılığı: ",altın[1]/(365*2-altın[0]))
print("Artıştan sonra sabit kalma olasılığı: ",altın[2]/(365*2-altın[0]))
print("Toplam: ",altın[1]/(365*2-altın[0])+altın[2]/(365*2-altın[0]))

print("Sabit kaldıkdan sonra artış olasılığı: ",altın[0]/(365*2-altın[1]))
print("Sabit kaldıkdan sonra azalış olasılığı: ",altın[2]/(365*2-altın[1]))
print("Toplam: ",altın[0]/(365*2-altın[1])+altın[2]/(365*2-altın[1]))

Artış olasılığı:  0.3315068493150685
Toplam 1.0
Azalıştan sonra artış olasılığı:  0.4782608695652174
Azalıştan sonra sabit kalma olasılığı:  0.5217391304347826
Toplam:  1.0
Artıştan sonra azalış olasılığı:  0.5409836065573771
Artıştan sonra sabit kalma olasılığı:  0.45901639344262296
Toplam:  1.0
Sabit kaldıkdan sonra artış olasılığı:  0.51931330472103
Sabit kaldıkdan sonra azalış olasılığı:  0.48068669527896996
Toplam:  1.0


Soru 4
60 adet cümle bularak yada yazarak biribine benzer olursa güzel olur.
Bunları sparse matrix haline dönüştürmeniz gerekmektedir.
Sonuçta hangi kelimeden sonra hangi kelimenin gelme olasılığı

In [ ]:
import random
import pandas as pd

df = pd.read_excel("MainDataset.xlsx")

cumleler = df["comments"].head(60)

import string
def remove_punctuation(text):
    no_punct = "".join([c for c in text if c not in string.punctuation])
    return no_punct

cumleler = cumleler.apply(lambda x: remove_punctuation(x))

from nltk.tokenize import word_tokenize
cumleler = [word_tokenize(i) for i in cumleler]
lowercase = []
for i in cumleler:
    lowercase.append([word.lower() for word in i])

words = []
for i in lowercase:
    for j in i:
        words.append(j)#%% md
Soru 1)
Dersteki pi sayısını bulma tarzında monte carlo yöntemleri gibi, 1 zarı 10000 kere atıp 1 2 3 4 5 6 sayılarını gelme olasılıkları

In [ ]:
import random

sayi = 10000

zar = [0,0,0,0,0,0]

for i in range(sayi):
    x = random.random()
    if x < 1/6:
        zar[0] += 1
    elif x < 2/6:
        zar[1] += 1
    elif x < 3/6:
        zar[2] += 1
    elif x < 4/6:
        zar[3] += 1
    elif x < 5/6:
        zar[4] += 1
    else:
        zar[5] += 1

for i in range(6):
    print(i+1,"gelme olasılığı: ",zar[i]/sayi)

print("Toplam: ",sum(zar)/sayi)

Soru 2)
Marko chain yöntemlerini kullanarak 1 yıllık bir kişinin yemek yeme datasını oluşturarak rastgele (hamburger,pizza, lahmancun olacak sadece)
Hamburger-hamburger,
hamburger-pizza,
hamburger lahmancun gelme olaslıklarını hesaplayınız.
*Not: bunu pizza ve lahmacun içinde yapınız


In [ ]:
import random

yemekler = ["hamburger","pizza","lahmacun"]
yemek = [0,0,0]

for i in range(365):
    x = random.random()
    if x < 1/3:
        yemek[0] += 1
    elif x < 2/3:
        yemek[1] += 1
    else:
        yemek[2] += 1

print("Hamburger gelme olasılığı: ",yemek[0]/365)
print("Pizza gelme olasılığı: ",yemek[1]/365)
print("Lahmacun gelme olasılığı: ",yemek[2]/365)


print("Hamburgerden sonra pizza gelme olasılığı: ",yemek[1]/(365-yemek[0]))
print("Hamburgerden sonra lahmacun gelme olasılığı: ",yemek[2]/(365-yemek[0]))
print("Toplam: ",yemek[1]/(365-yemek[0])+yemek[2]/(365-yemek[0]))


print("Pizzadan sonra lahmacun gelme olasılığı: ",yemek[2]/(365-yemek[1]))
print("Pizzadan sonra hamburger gelme olasılığı: ",yemek[0]/(365-yemek[1]))
print("Toplam: ",yemek[2]/(365-yemek[1])+yemek[0]/(365-yemek[1]))


print("Lahmacundan sonra hamburger gelme olasılığı: ",yemek[0]/(365-yemek[2]))
print("Lahmacundan sonra pizza gelme olasılığı: ",yemek[1]/(365-yemek[2]))
print("Toplam: ",yemek[0]/(365-yemek[2])+yemek[1]/(365-yemek[2]))

Soru 3)
2 yıllık altın fiyatı oluşturunuz rastgele 800 ve 1000 arasında
Yine markov chain artış azalış sabit kalma 3 durum. olasılıklarınız çıkarınız.
Örnek ilk veriniz 800 sonraki veriniz 810 bu artış
ilk veriniz 900 sonraki veriniz 850 azalış
850 - 850 ise sabit şekilde kategorik hale getirip markov chain uygulayınız

In [ ]:
import random

olasılıklar = ["artış","azalış","sabit"]

altın = [0,0,0]

for i in range(365*2):
    x = random.random()
    if x < 1/3:
        altın[0] += 1
    elif x < 2/3:
        altın[1] += 1
    else:
        altın[2] += 1

print("Artış olasılığı: ",altın[0]/(365*2))
print("Toplam", altın[0]/(365*2)+altın[1]/(365*2)+altın[2]/(365*2))


print("Azalıştan sonra artış olasılığı: ",altın[0]/(365*2-altın[2]))
print("Azalıştan sonra sabit kalma olasılığı: ",altın[1]/(365*2-altın[2]))
print("Toplam: ",altın[0]/(365*2-altın[2])+altın[1]/(365*2-altın[2]))

print("Artıştan sonra azalış olasılığı: ",altın[1]/(365*2-altın[0]))
print("Artıştan sonra sabit kalma olasılığı: ",altın[2]/(365*2-altın[0]))
print("Toplam: ",altın[1]/(365*2-altın[0])+altın[2]/(365*2-altın[0]))

print("Sabit kaldıkdan sonra artış olasılığı: ",altın[0]/(365*2-altın[1]))
print("Sabit kaldıkdan sonra azalış olasılığı: ",altın[2]/(365*2-altın[1]))
print("Toplam: ",altın[0]/(365*2-altın[1])+altın[2]/(365*2-altın[1]))

Soru 4
60 adet cümle bularak yada yazarak biribine benzer olursa güzel olur.
Bunları sparse matrix haline dönüştürmeniz gerekmektedir.
Sonuçta hangi kelimeden sonra hangi kelimenin gelme olasılığı

In [87]:
import random
import pandas as pd

df = pd.read_excel("MainDataset.xlsx")

cumleler = df["comments"].head(60)

In [88]:
import string
def remove_punctuation(text):
    no_punct = "".join([c for c in text if c not in string.punctuation])
    return no_punct

cumleler = cumleler.apply(lambda x: remove_punctuation(x))

from nltk.tokenize import word_tokenize
cumleler = [word_tokenize(i) for i in cumleler]
lowercase = []
for i in cumleler:
    lowercase.append([word.lower() for word in i])

words = []
for i in lowercase:
    for j in i:
        words.append(j)

words

['beyaz',
 'takımın',
 'alt',
 'kısmı',
 'çok',
 'ince',
 've',
 'biraz',
 'rahatsız',
 'ediyor',
 '165',
 'boy',
 '56',
 'kilo',
 '80',
 'beden',
 'göğüs',
 'l',
 'aldm',
 'xl',
 'alsam',
 'daha',
 'iyi',
 'olurmuş',
 'siyah',
 'takım',
 'çok',
 'rahat',
 've',
 'esnek',
 'kendi',
 'bedeninizden',
 'bir',
 'beden',
 'büyük',
 'alabilirsiniz',
 'rahatınıza',
 'düşkünseniz',
 'kahverenginin',
 'kumaşı',
 'ise',
 'siyaha',
 'göre',
 'bir',
 'tık',
 'kalın',
 'fiyatina',
 'gelecek',
 'olursam',
 'normal',
 'bir',
 'ic',
 'çamaşırı',
 '20',
 '30tl',
 'bir',
 'takim',
 '50tlye',
 'çok',
 'degil',
 'bencebir',
 'yıldızı',
 'da',
 'tüm',
 'ürünlerin',
 'kumaso',
 've',
 'esnekliği',
 'birbirinden',
 'kesinlikle',
 '1',
 'beden',
 'büyük',
 'tercih',
 'edilmeli',
 'kalite',
 'olarakta',
 'normal',
 'çok',
 'bişey',
 'beklemeyin',
 'tek',
 'kelimeyle',
 'rezalet',
 'xl',
 'beden',
 'sipariş',
 'verdim',
 'elime',
 'gelen',
 'ürün',
 'xs',
 'ayrıca',
 'üzerinde',
 'beden',
 'numarası',
 'yok',
 

In [89]:
from collections import Counter
counts = Counter(words)
counts

Counter({'beyaz': 1,
         'takımın': 1,
         'alt': 1,
         'kısmı': 1,
         'çok': 27,
         'ince': 3,
         've': 14,
         'biraz': 12,
         'rahatsız': 2,
         'ediyor': 1,
         '165': 2,
         'boy': 1,
         '56': 1,
         'kilo': 2,
         '80': 1,
         'beden': 30,
         'göğüs': 1,
         'l': 10,
         'aldm': 1,
         'xl': 4,
         'alsam': 2,
         'daha': 13,
         'iyi': 5,
         'olurmuş': 2,
         'siyah': 2,
         'takım': 3,
         'rahat': 13,
         'esnek': 5,
         'kendi': 13,
         'bedeninizden': 2,
         'bir': 20,
         'büyük': 12,
         'alabilirsiniz': 7,
         'rahatınıza': 1,
         'düşkünseniz': 1,
         'kahverenginin': 1,
         'kumaşı': 6,
         'ise': 1,
         'siyaha': 1,
         'göre': 6,
         'tık': 1,
         'kalın': 5,
         'fiyatina': 1,
         'gelecek': 1,
         'olursam': 1,
         'normal': 2,
         

In [91]:
import numpy as np
from scipy.sparse import dok_matrix

n_words = len(words)

sparse_matrix = dok_matrix((n_words, n_words))

# Populate the matrix with the words as the labels for the rows and columns
for i, word_i in enumerate(words):
    for j, word_j in enumerate(words):
        if word_i == word_j:
            sparse_matrix[i, j] = 1

print(sparse_matrix.todense())

[[1. 0. 0. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]
 [0. 0. 1. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 1. 0. 0.]
 [0. 0. 0. ... 0. 1. 0.]
 [0. 0. 0. ... 0. 0. 1.]]
